name: CD-terraform Plan Destroy

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: Select module to remove
        required: true
        default: supervision
        options:
          - supervision
          - terraformtest
      environment:
        type: choice
        description: Select environment to remove
        required: true
        default: preproduction
        options:
          - preproduction
          - production
      aws-region:
        type: choice
        description: Select AWS region zone
        required: true
        default: eu-central-1
        options:
          - eu-central-1
      destroy:
        description: Launch Terraform destroy ?
        required: true
        type: boolean
        default: false

env:
  TERRAFORM_VERSION : 1.1.6
  
# permission can be added at job level or workflow level
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  Deployment:
    name: Module ${{ inputs.module }} deployment.
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: test pipeline
        id: checkout-management
        uses: actions/checkout@v2
      - name : test run  
        run: echo helloworld
       
      - name : testing terraform deploy
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: Terraform init
        id: init
        run: terraform init
        shell: bash
        working-directory: .
      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false
      - name: Terraform apply
        id: apply
        run: terraform apply -input=false   
